steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-central2-docker.pkg.dev/my-reddit-scrapper/reddit-scraper-repo/reddit-scraper',
      '-f', 'Dockerfile',
      '.'
    ]
    dir: reddit_scraper

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-central2-docker.pkg.dev/my-reddit-scrapper/reddit-scraper-repo/reddit-scraper'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'reddit-scraper',
      '--image', 'europe-central2-docker.pkg.dev/my-reddit-scrapper/reddit-scraper-repo/reddit-scraper',
      '--region', 'europe-central2',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY